"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.toPptxTheme = exports.toMarpTheme = exports.toTelegramTheme = exports.toDtcgJson = exports.toFlatJson = exports.toEmailInline = exports.toPdfCss = exports.toDocxStyles = exports.toTailwindConfig = exports.cssVariablesToRootBlock = exports.darkModeCssVariables = exports.brandToCssVariables = exports.toWebCss = exports.kebab = exports.resolveColors = exports.checkBrand = exports.validateBrand = void 0;
var validate_1 = require("./validate");
Object.defineProperty(exports, "validateBrand", { enumerable: true, get: function () { return validate_1.validateBrand; } });
Object.defineProperty(exports, "checkBrand", { enumerable: true, get: function () { return validate_1.checkBrand; } });
var shared_1 = require("./transformers/shared");
Object.defineProperty(exports, "resolveColors", { enumerable: true, get: function () { return shared_1.resolveColors; } });
Object.defineProperty(exports, "kebab", { enumerable: true, get: function () { return shared_1.kebab; } });
var toWebCss_1 = require("./transformers/toWebCss");
Object.defineProperty(exports, "toWebCss", { enumerable: true, get: function () { return toWebCss_1.toWebCss; } });
Object.defineProperty(exports, "brandToCssVariables", { enumerable: true, get: function () { return toWebCss_1.brandToCssVariables; } });
Object.defineProperty(exports, "darkModeCssVariables", { enumerable: true, get: function () { return toWebCss_1.darkModeCssVariables; } });
Object.defineProperty(exports, "cssVariablesToRootBlock", { enumerable: true, get: function () { return toWebCss_1.cssVariablesToRootBlock; } });
var toTailwindConfig_1 = require("./transformers/toTailwindConfig");
Object.defineProperty(exports, "toTailwindConfig", { enumerable: true, get: function () { return toTailwindConfig_1.toTailwindConfig; } });
var toDocxStyles_1 = require("./transformers/toDocxStyles");
Object.defineProperty(exports, "toDocxStyles", { enumerable: true, get: function () { return toDocxStyles_1.toDocxStyles; } });
var toPdfCss_1 = require("./transformers/toPdfCss");
Object.defineProperty(exports, "toPdfCss", { enumerable: true, get: function () { return toPdfCss_1.toPdfCss; } });
var toEmailInline_1 = require("./transformers/toEmailInline");
Object.defineProperty(exports, "toEmailInline", { enumerable: true, get: function () { return toEmailInline_1.toEmailInline; } });
var toFlatJson_1 = require("./transformers/toFlatJson");
Object.defineProperty(exports, "toFlatJson", { enumerable: true, get: function () { return toFlatJson_1.toFlatJson; } });
var toDtcgJson_1 = require("./transformers/toDtcgJson");
Object.defineProperty(exports, "toDtcgJson", { enumerable: true, get: function () { return toDtcgJson_1.toDtcgJson; } });
var toTelegramTheme_1 = require("./transformers/toTelegramTheme");
Object.defineProperty(exports, "toTelegramTheme", { enumerable: true, get: function () { return toTelegramTheme_1.toTelegramTheme; } });
var toMarpTheme_1 = require("./transformers/toMarpTheme");
Object.defineProperty(exports, "toMarpTheme", { enumerable: true, get: function () { return toMarpTheme_1.toMarpTheme; } });
var toPptxTheme_1 = require("./transformers/toPptxTheme");
Object.defineProperty(exports, "toPptxTheme", { enumerable: true, get: function () { return toPptxTheme_1.toPptxTheme; } });
